---
driver:
  name: vagrant
  linked_clones: true
  gui: false
  communicator: winrm
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: dsc

transport:
  name: winrm

verifier:
  name: pester
  test_folder: Tests/Integration

platforms:
  - name: windows-2012r2-wmf4
    driver:
      box: mwrock/Windows2012R2
      network: 
        - ["forwarded_port", {guest: 80, host: 8080}]
    provisioner:
      dsc_local_configuration_manager_version: wmf4_with_update

suites:
  - name: ExampleConfig
    provisioner:
      modules_path: Modules
      configuration_script_folder: Configurations
      configuration_script: ExampleConfig.ps1
      configuration_name: ExampleConfig
      configuration_data:
        AllNodes:
          - NodeName: localhost
            ExampleFolder: "c:\\dsc\\Example"
      